### ISSUE TITLE
Black canvas sketch filter

### ISSUE THREAD

**Issue by johri002** [NJACKWinterOfCode/Image-Filters#21]
The filter that converts an image as a colored black chalkboard drawing.

**Input image:**
![farm](https://user-images.githubusercontent.com/30645315/49465750-4bdbb080-f824-11e8-9c37-002603e9d0e1.png)

**Rendered image:**
![black board drawing](https://user-images.githubusercontent.com/30645315/49465782-5c8c2680-f824-11e8-8858-bbaac85ebc6e.jpg)

**Comment by adityaRakhecha** [comment]
You should have referenced Issue #6 every time you are making a new filter, as the issue says instead of opening a new issue.
